# Generated by Django 3.2.7 on 2021-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='')),
                ('image_type', models.CharField(choices=[('Nature', 'Nature'), ('Space', 'Space'), ('Urban', 'Urban'), ('Abstract', 'Abstract')], max_length=10)),
            ],
        ),
    ]
